version: '3.1'

services:
    wordpress:
        image: wordpress
        restart: always
        ports:
            - 5555:80
        environment:
            WORDPRESS_DB_HOST: db
            WORDPRESS_DB_USER: ${DB_USER}
            WORDPRESS_DB_PASSWORD: ${DB_PASS}
            WORDPRESS_DB_NAME: ${DB_NAME}
        volumes:
            - ./wordpress:/var/www/html

    db:
        image: mariadb
        restart: always
        environment:
            MYSQL_DATABASE: ${DB_NAME}
            MYSQL_USER: ${DB_USER}
            MYSQL_PASSWORD: ${DB_PASS}
            MYSQL_RANDOM_ROOT_PASSWORD: '1'
        volumes:
            - ./db_data:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
            - 8080:80
        environment:
            - PMA_ARBITRARY=1